# PYTHON ASSIGNMENT-2

# REG NO: 21UAI072


# INHERITANCE
## SINGLE INHERTANCE

In [3]:
# single inheritance using protected access modifier
class emp:
    def __init__(self,name,gender):
        #protected data members initialization
        self._name=name
        self._gender=gender
class hr(emp):
    def display(self):
        print("NAME:",self._name)
        print("GENDER:",self._gender)
    def dec(self):
        print('Student')
hrobj=hr('tamil','male')
hrobj.display()
hrobj.dec()

NAME: tamil
GENDER: male
Student


## MULTILEVEL INHERITANCE

In [4]:
class Family:
    def show_family(self):
        print("This is our family:")
 
 
# Father class inherited from Family
class Father(Family):
    fathername = ""
 
    def show_father(self):
        print(self.fathername)
 
 
# Mother class inherited from Family
class Mother(Family):
    mothername = ""
 
    def show_mother(self):
        print(self.mothername)
 
 
# Son class inherited from Father and Mother classes
class Son(Father, Mother):
    def show_parent(self):
        print("Father :", self.fathername)
        print("Mother :", self.mothername)
 
 
s1 = Son()  # Object of Son class
s1.fathername = "Mark"
s1.mothername = "Sonia"
s1.show_family()
s1.show_parent()

This is our family:
Father : Mark
Mother : Sonia


## MULTIPLE INHERITANCE

In [8]:
# Python Program to depict multiple inheritance
# when method is overridden in both classes

class Class1:
    def m(self):
        print("In Class1")
class Class2(Class1):
    def m(self):
        print("In Class2")

class Class3(Class1):
    def m(self):
        print("In Class3")
class Class4(Class2, Class3):
    pass
obj = Class4()
obj.m()

In Class2


## HIERARCHIAL INHERITANCE

In [10]:
# Python program to demonstrate
# single inheritance

# Base class
class Parent:
    def func1(self):
        print("This function is in parent class.")

# Derived class


class Child(Parent):
    def func2(self):
        print("This function is in child class.")


# Driver's code
object = Child()
object.func1()
object.func2()


This function is in parent class.
This function is in child class.


## HYBRID INHERITANCE

In [12]:
class GrandPa:
    def __init__(self):
        print("Grand father")

class Father(GrandPa):
    def __init__(self):
        super().__init__()
        print("Father")

class Mother(GrandPa):
    def __init__(self):
        super().__init__()
        print("Mother")


class child(Father, Mother):
    def __init__(self):
        super().__init__()
        print("Child")

a = child()


Grand father
Mother
Father
Child


## ACCESS MODIFIERS

In [57]:
#private inheritance
class emp:
    def __init__(self,eid,name):
        self._eid=eid
        self._name=name
e1=emp(3,'HI')
e1._eid

3

In [15]:
#private data members initialization
class emp:
    def __init__(self,emid,name):
        self.__eid=emid 
        self.__ename=name
e1=emp(1,"P")

# protected data members initialization
class job:
    def __init__(self,name,role):
        self._name=name 
        self._role=role
    def displaydata(self):
        print("name:",self._name)
        print("role:",self._role)
class hr(job):
    print("SDE")
o1=hr('SAKTHI','STUDENT') 
o1.displaydata()



SDE
name: SAKTHI
role: STUDENT


In [16]:
#public data members initialization
class emp:
    def __init__(self,name,height,weight):
        self.sname=name # all data members are public by default 
        self.sheight=height # . is used to initialize public data members
        self.sweight=weight
    def display(self):
        print("NAME:",self.sname)
        print("HEIGHT:",self.sheight)
        print("WEIGHT:",self.sweight)
o1=emp('SAKTHI',170,55)
o1.display()

NAME: SAKTHI
HEIGHT: 170
WEIGHT: 55


## NUMPY AGGREGATORS

In [18]:
import numpy as np
x=np.array([[1,3,5,2],[5,3,5,5],[9,1,1,2]])
print(np.max(x),np.min(x),np.sum(x))

9 1 42


In [20]:
a=np.random.randint(1,50,(3,4))
print(a)
print(a.sum())
print("sum row-wise:",np.sum(x,axis=1))
print("sum col-wise:",np.sum(x,axis=0))
print("max element of each col:",np.max(x,axis=0))
print("min element of each col:",np.min(x,axis=0))


[[10 46 40  6]
 [25 21 46 37]
 [16 16 39 24]]
326
sum row-wise: [11 18 13]
sum col-wise: [15  7 11  9]
max element of each col: [9 3 5 5]
min element of each col: [1 1 1 2]


In [22]:
import numpy as np
print(np.product([[1,6],[2,4]]))
print(np.mean([[2,6],[6,8]]))
print(np.std([[2,4],[6,4]]))
print(np.var([[2,2],[6,8]]))
x=np.array([[2,4],[6,2]])
print(np.argmax([1,2,3,4]))
print(np.argmin([1,2,3,4]))
n=np.array([True,True,True,False])
print(np.all(n))
print(np.any(n))
print(np.median([1,2,3,4,5]))

48
5.5
1.4142135623730951
6.75
3
0
False
True
3.0


## COMPARISION,MASKS AND BOOLEAN ARRAYS IN NUMPY

In [63]:
#boolean operations
import numpy as np
x=np.array([1,2,5,3,2])
print(x<2)
print(x>2)
print(x<=2)
print(x>=2)
print(x!=2)
print(x==2)

[ True False False False False]
[False False  True  True False]
[ True  True False False  True]
[False  True  True  True  True]
[ True False  True  True False]
[False  True False False  True]


In [64]:
4*x==(x**4)

array([False, False, False, False, False])

In [65]:
bool(22 and 0)

False

In [66]:
x=np.array([1,3,1,0,1,1],dtype=bool)
y=np.array([1,1,1,0,1,0],dtype=bool)

In [67]:
x&y

array([ True,  True,  True, False,  True, False])

In [68]:
x|y

array([ True,  True,  True, False,  True,  True])

In [69]:
x!=y

array([False, False, False, False, False,  True])

In [70]:
x^y

array([False, False, False, False, False,  True])

In [71]:
np.all(x) 

False

In [72]:
np.any(y)

True

## EXCEPTION HANDLING

In [23]:
#zero division error
def fun(a,b):
    try:
        c=a+b/(a-b)
    except ZeroDivisionError:
        print("Error due to divided by 0")
        
    else:
        print(c)
    finally:
        print("error")
fun(2,2)      

    

Error due to divided by 0
error


In [24]:
cgpa=9
try:
    if(cgpa>9):
        print("good")
except SyntaxError:
    print("syntax error")



In [27]:
list1 = ['x',3, 2, 3,-9.6]
try: 
    print ("third element =",list1[2])
    print ("Sixth element =",list1[5]) #trying to access out of range element
except:
    print ("error")

third element = 2
error


In [29]:
def func1(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("dividing a/b is 0")
    else:
        print (c)  
        
func1(0,1)
func1(3,8)

-1.0
-2.2


In [30]:
try:
    raise NameError("hello") # Raise Error
except NameError:
    print ("error")
    

error
